<!DOCTYPE HTML>
<html>
<header>
<title>Ghoul World New Home Page</title>
<link rel="stylesheet" href="frontend/HTML/CSS/style.css" type="text/css" />
</header>
<body>
<section id="banner"><p id="logo">Ghoul World</p></section>
<section id="content">
	<section id="leftnav">
		
	</section>
	<section id="stage">
		{{ content }}
	</section>
</section>
<footer id="copyright"><p><i>Copyright © 2015 Tragic Clown Productions All Rights Reserved<i></p></footer>
</body>
</html>