<!DOCTYPE HTML>
<html>
<header>
<title>Ghoul World New Home Page</title>
<link rel="stylesheet" href="frontend/HTML/CSS/style.css" type="text/css" />
</header>
<body>
<div id="banner"><p id="logo">Ghoul World</p></div>
<div id="content">
<form action="?id=1" name="login" method="post">
				<table id="login">
					<tbody>
						<tr><td>{{ message }}</td></tr>
						<tr><td><i>Login to Ghoul World</i></tr></td>
						<tr><td><input value="username" name="username" type="text"></td></tr>
						<tr><td><input value="password" name="password" type="password"></td></tr>
						<tr><td><input value="submit" type="submit"></td></tr>
					</tbody>
				</table>
			</form>
</div>
<footer id="copyright"><p><i>Copyright © 2015 Tragic Clown Productions All Rights Reserved<i></p></footer>
</body>
</html>