<div id="phone">
			<div id="screen">
				<table id="screen_grid">
				<tr id="t_half">
					<td>
						<table class="app_grid" id="phone_content">
						<tr>
							<td></td><td></td><td></td><td></td>
						</tr>
						<tr>
							<td></td><td></td><td></td><td></td>
						</tr>
						<tr>
							<td></td><td></td><td></td><td></td>
						</tr>
						<tr>
							<td></td><td></td><td></td><td></td>
						</tr>
						<tr>
							<td></td><td></td><td></td><td></td>
						</tr>
						</table>
					</td>
				</tr>
				<tr id="b_half">
					<td>
						<table class="app_grid" id="phone_menu">
							<tr>
								<td><img src="/ghoul/frontend/HTML/images/icons/phone/white/ic_settings_white_24dp.png" /></td>
								<td><img src="/ghoul/frontend/HTML/images/icons/phone/white/ic_chat_white_24dp.png" /></td>
								<td><img src="/ghoul/frontend/HTML/images/icons/phone/white/app_drawer_white.png" /></td>
								<td><img src="/ghoul/frontend/HTML/images/icons/phone/white/ic_PM_white_24dp.png" /></td>
								<td><img src="/ghoul/frontend/HTML/images/icons/phone/white/ic_info_white_24dp.png" /></td>
							</tr>
						</table>
					</td>
				</tr>
				</table>
			</div>
		</div>